name: Lift Results To IQ
 
on:
  push:
    branches:
      - main
  release:
    types: # This configuration does not affect the page_build event above
      - created
 
jobs:
  lift_analyze:
    name: Lift Analysis
    runs-on: ubuntu-latest
    container:
        image: musedev/analyst
        credentials:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
        # - name: Setup build environment
        #   env:
        #       nexus_token: ${{ secrets.MY_NEXUS_TOKEN }}
        #   run: |
        #       ... put shell script to create .m2/settings.xml
        #       .... put shell script to install build dependencies if needed
        - name: Produce Lift Artifact
          run: |
              if [ -z "$GITHUB_BASE_REF" ] ; then
                export DST_SHA="$GITHUB_SHA"
              else
                export DST_SHA=$(cat $GITHUB_EVENT_PATH | jq -r -j .pull_request.base.sha)
              fi
              analyst -t "$GITHUB_WORKSPACE" -C $DST_SHA > lift-output.json
              cat lift-output.json | jq . | sed 's/\\n/\n/g'
        - name: Upload dst artifact
          uses: actions/upload-artifact@v2
          with:
            name: lift_output
            path: lift-output.json
 
  send_results_to_sonatype_iq:
    name: Send results to Sonatype IQ
    needs: [lift_analyze]
    runs-on: ubuntu-latest
    container:
        image: musedev/github-comment-composer
        credentials:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
        - name: Get Results
          uses: actions/download-artifact@v2
          with:
            name: lift_output
        - shell: bash
          name: Push to IQ
          env:
              SONATYPE_NEXUS_IQ_APPLICATION_ID: ${{ secrets.SONATYPE_NEXUS_IQ_APPLICATION_ID }}
              SONATYPE_NEXUS_IQ_URL: ${{ secrets.SONATYPE_NEXUS_IQ_URL }}
              SONATYPE_NEXUS_IQ_STAGE: ${{ secrets.SONATYPE_NEXUS_IQ_STAGE }}
              SONATYPE_NEXUS_IQ_USER: ${{ secrets.SONATYPE_NEXUS_IQ_USER }}
              SONATYPE_NEXUS_IQ_PASSWORD: ${{ secrets.SONATYPE_NEXUS_IQ_PASSWORD }}
          run: |
            /opt/bin/push-to-iq.sh
